
  CREATE TABLE "MCHARGE"."LOT_LOTTERY_NUMBER" 
   (	"LOT_DT" VARCHAR2(20 BYTE), 
	"NUM_1" NUMBER(3,0), 
	"NUM_2" NUMBER(3,0), 
	"NUM_3" NUMBER(3,0), 
	"NUM_4" NUMBER(3,0), 
	"NUM_5" NUMBER(3,0), 
	"NUM_6" NUMBER(3,0), 
	"NUM_B" NUMBER(3,0), 
	"LOT_NUM" VARCHAR2(5 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_MCHARGE" ;
 
