CREATE TABLE COM_USER
(
  USER_NO VARCHAR2(20) NOT NULL,
  USER_NM VARCHAR2(20),
  LOGIN_ID VARCHAR2(20),
  LOGIN_PW VARCHAR2(20),
  CLIENT_IP VARCHAR2(20),
  WRONG_PW_CNT NUMBER(4,0),
  LAST_LOGIN_DT DATE,
  CONSTRAINT COM_USER_PK PRIMARY KEY ( USER_NO ) ENABLE
)
;

-- 성경
create table BIBLE_MASTER (
  BOOK_SEQ        NUMBER(5,0),
  BOOK_NM_KOR     varchar(50),
  BOOK_NM_KOR_ABR varchar(50),
  BOOK_NM_ENG     varchar(50),
  BOOK_NM_ENG_ABR varchar(50),
  LAST_PAGE       NUMBER(5,0),
  CONSTRAINT BIBLE_MASTER_PK PRIMARY KEY ( BOOK_SEQ ) ENABLE
);



INSERT INTO "SCAL"."BIBLE_MASTER" (BOOK_NM_KOR, BOOK_NM_KOR_ABR, BOOK_NM_ENG, BOOK_NM_ENG_ABR, LAST_PAGE) VALUES ('창세기', '창', 'Genesis', 'GEN', '50')
INSERT INTO "SCAL"."BIBLE_MASTER" (BOOK_NM_KOR, BOOK_NM_KOR_ABR, BOOK_NM_ENG, BOOK_NM_ENG_ABR, LAST_PAGE) VALUES ('출애굽기', '출', 'Exodus', 'EXO', '40')
INSERT INTO "SCAL"."BIBLE_MASTER" (BOOK_NM_KOR, BOOK_NM_KOR_ABR, BOOK_NM_ENG, BOOK_NM_ENG_ABR, LAST_PAGE) VALUES ('레위기', '레', 'Leviticus', 'LEV', '27')
INSERT INTO "SCAL"."BIBLE_MASTER" (BOOK_NM_KOR, BOOK_NM_KOR_ABR, BOOK_NM_ENG, BOOK_NM_ENG_ABR, LAST_PAGE) VALUES ('민수기', '민', 'Numbers', 'NUM', '36')
INSERT INTO "SCAL"."BIBLE_MASTER" (BOOK_NM_KOR, BOOK_NM_KOR_ABR, BOOK_NM_ENG, BOOK_NM_ENG_ABR, LAST_PAGE) VALUES ('신명기', '신', 'Deuteronomy', 'DEU', '34')
INSERT INTO "SCAL"."BIBLE_MASTER" (BOOK_NM_KOR, BOOK_NM_KOR_ABR, BOOK_NM_ENG, BOOK_NM_ENG_ABR, LAST_PAGE) VALUES ('여호수아', '수', 'Joshua', 'JOS', '24')
INSERT INTO "SCAL"."BIBLE_MASTER" (BOOK_NM_KOR, BOOK_NM_KOR_ABR, BOOK_NM_ENG, BOOK_NM_ENG_ABR, LAST_PAGE) VALUES ('사사기', '삿', 'Judges', 'JDG', '21')
INSERT INTO "SCAL"."BIBLE_MASTER" (BOOK_NM_KOR, BOOK_NM_KOR_ABR, BOOK_NM_ENG, BOOK_NM_ENG_ABR, LAST_PAGE) VALUES ('룻기', '룻', 'Ruth', 'RTH', '4')
INSERT INTO "SCAL"."BIBLE_MASTER" (BOOK_NM_KOR, BOOK_NM_KOR_ABR, BOOK_NM_ENG, BOOK_NM_ENG_ABR, LAST_PAGE) VALUES ('사무엘상', '삼상', '1Samuel', 'SA1', '31')
INSERT INTO "SCAL"."BIBLE_MASTER" (BOOK_NM_KOR, BOOK_NM_KOR_ABR, BOOK_NM_ENG, BOOK_NM_ENG_ABR, LAST_PAGE) VALUES ('사무엘하', '삼하', '2Samuel', 'SA2', '24')
INSERT INTO "SCAL"."BIBLE_MASTER" (BOOK_NM_KOR, BOOK_NM_KOR_ABR, BOOK_NM_ENG, BOOK_NM_ENG_ABR, LAST_PAGE) VALUES ('열왕기상', '왕상', '1Kings', 'KI1', '22')
INSERT INTO "SCAL"."BIBLE_MASTER" (BOOK_NM_KOR, BOOK_NM_KOR_ABR, BOOK_NM_ENG, BOOK_NM_ENG_ABR, LAST_PAGE) VALUES ('열왕기하', '왕하', '2Kings', 'KI2', '25')
INSERT INTO "SCAL"."BIBLE_MASTER" (BOOK_NM_KOR, BOOK_NM_KOR_ABR, BOOK_NM_ENG, BOOK_NM_ENG_ABR, LAST_PAGE) VALUES ('역대상', '대상', '1Chronicles', 'CH1', '29')
INSERT INTO "SCAL"."BIBLE_MASTER" (BOOK_NM_KOR, BOOK_NM_KOR_ABR, BOOK_NM_ENG, BOOK_NM_ENG_ABR, LAST_PAGE) VALUES ('역대하', '대하', '2Chronicles', 'CH2', '36')
INSERT INTO "SCAL"."BIBLE_MASTER" (BOOK_NM_KOR, BOOK_NM_KOR_ABR, BOOK_NM_ENG, BOOK_NM_ENG_ABR, LAST_PAGE) VALUES ('에스라', '스', 'Ezra', 'EZR', '10')
INSERT INTO "SCAL"."BIBLE_MASTER" (BOOK_NM_KOR, BOOK_NM_KOR_ABR, BOOK_NM_ENG, BOOK_NM_ENG_ABR, LAST_PAGE) VALUES ('느헤미야', '느', 'Nehemiah', 'NEH', '13')
INSERT INTO "SCAL"."BIBLE_MASTER" (BOOK_NM_KOR, BOOK_NM_KOR_ABR, BOOK_NM_ENG, BOOK_NM_ENG_ABR, LAST_PAGE) VALUES ('에스더', '에', 'Esther', 'EST', '10')
INSERT INTO "SCAL"."BIBLE_MASTER" (BOOK_NM_KOR, BOOK_NM_KOR_ABR, BOOK_NM_ENG, BOOK_NM_ENG_ABR, LAST_PAGE) VALUES ('욥기', '욥', 'Job', 'JOB', '42')
INSERT INTO "SCAL"."BIBLE_MASTER" (BOOK_NM_KOR, BOOK_NM_KOR_ABR, BOOK_NM_ENG, BOOK_NM_ENG_ABR, LAST_PAGE) VALUES ('시편', '시', 'Psalms', 'PSA', '150')
INSERT INTO "SCAL"."BIBLE_MASTER" (BOOK_NM_KOR, BOOK_NM_KOR_ABR, BOOK_NM_ENG, BOOK_NM_ENG_ABR, LAST_PAGE) VALUES ('잠언', '잠', 'Proverbs', 'PRO', '31')
INSERT INTO "SCAL"."BIBLE_MASTER" (BOOK_NM_KOR, BOOK_NM_KOR_ABR, BOOK_NM_ENG, BOOK_NM_ENG_ABR, LAST_PAGE) VALUES ('전도서', '전', 'Ecclesiastes', 'ECC', '12')
INSERT INTO "SCAL"."BIBLE_MASTER" (BOOK_NM_KOR, BOOK_NM_KOR_ABR, BOOK_NM_ENG, BOOK_NM_ENG_ABR, LAST_PAGE) VALUES ('아가', '아', 'SongofSongs', 'SON', '8')
INSERT INTO "SCAL"."BIBLE_MASTER" (BOOK_NM_KOR, BOOK_NM_KOR_ABR, BOOK_NM_ENG, BOOK_NM_ENG_ABR, LAST_PAGE) VALUES ('이사야', '사', 'Isaiah', 'ISA', '66')
INSERT INTO "SCAL"."BIBLE_MASTER" (BOOK_NM_KOR, BOOK_NM_KOR_ABR, BOOK_NM_ENG, BOOK_NM_ENG_ABR, LAST_PAGE) VALUES ('예레미야', '렘', 'Jeremiah', 'JER', '52')
INSERT INTO "SCAL"."BIBLE_MASTER" (BOOK_NM_KOR, BOOK_NM_KOR_ABR, BOOK_NM_ENG, BOOK_NM_ENG_ABR, LAST_PAGE) VALUES ('예레미야 애가', '애', 'Lamentations', 'LAM', '5')
INSERT INTO "SCAL"."BIBLE_MASTER" (BOOK_NM_KOR, BOOK_NM_KOR_ABR, BOOK_NM_ENG, BOOK_NM_ENG_ABR, LAST_PAGE) VALUES ('에스겔', '겔', 'Ezekiel', 'EZE', '48')
INSERT INTO "SCAL"."BIBLE_MASTER" (BOOK_NM_KOR, BOOK_NM_KOR_ABR, BOOK_NM_ENG, BOOK_NM_ENG_ABR, LAST_PAGE) VALUES ('다니엘', '단', 'Daniel', 'DAN', '12')
INSERT INTO "SCAL"."BIBLE_MASTER" (BOOK_NM_KOR, BOOK_NM_KOR_ABR, BOOK_NM_ENG, BOOK_NM_ENG_ABR, LAST_PAGE) VALUES ('호세아', '호', 'Hosea', 'HOS', '14')
INSERT INTO "SCAL"."BIBLE_MASTER" (BOOK_NM_KOR, BOOK_NM_KOR_ABR, BOOK_NM_ENG, BOOK_NM_ENG_ABR, LAST_PAGE) VALUES ('요엘', '욜', 'Joel', 'JOE', '3')
INSERT INTO "SCAL"."BIBLE_MASTER" (BOOK_NM_KOR, BOOK_NM_KOR_ABR, BOOK_NM_ENG, BOOK_NM_ENG_ABR, LAST_PAGE) VALUES ('아모스', '암', 'Amos', 'AMO', '9')
INSERT INTO "SCAL"."BIBLE_MASTER" (BOOK_NM_KOR, BOOK_NM_KOR_ABR, BOOK_NM_ENG, BOOK_NM_ENG_ABR, LAST_PAGE) VALUES ('오바댜', '옵', 'Obadiah', 'OBA', '1')
INSERT INTO "SCAL"."BIBLE_MASTER" (BOOK_NM_KOR, BOOK_NM_KOR_ABR, BOOK_NM_ENG, BOOK_NM_ENG_ABR, LAST_PAGE) VALUES ('요나', '욘', 'Jonah', 'JON', '4')
INSERT INTO "SCAL"."BIBLE_MASTER" (BOOK_NM_KOR, BOOK_NM_KOR_ABR, BOOK_NM_ENG, BOOK_NM_ENG_ABR, LAST_PAGE) VALUES ('미가', '미', 'Micah', 'MIC', '7')
INSERT INTO "SCAL"."BIBLE_MASTER" (BOOK_NM_KOR, BOOK_NM_KOR_ABR, BOOK_NM_ENG, BOOK_NM_ENG_ABR, LAST_PAGE) VALUES ('나훔', '나', 'Nahum', 'NAH', '3')
INSERT INTO "SCAL"."BIBLE_MASTER" (BOOK_NM_KOR, BOOK_NM_KOR_ABR, BOOK_NM_ENG, BOOK_NM_ENG_ABR, LAST_PAGE) VALUES ('하박국', '합', 'Habakkuk', 'HAB', '3')
INSERT INTO "SCAL"."BIBLE_MASTER" (BOOK_NM_KOR, BOOK_NM_KOR_ABR, BOOK_NM_ENG, BOOK_NM_ENG_ABR, LAST_PAGE) VALUES ('스바냐', '습', 'Zephaniah', 'ZEP', '3')
INSERT INTO "SCAL"."BIBLE_MASTER" (BOOK_NM_KOR, BOOK_NM_KOR_ABR, BOOK_NM_ENG, BOOK_NM_ENG_ABR, LAST_PAGE) VALUES ('학개', '학', 'Haggai', 'HAG', '2')
INSERT INTO "SCAL"."BIBLE_MASTER" (BOOK_NM_KOR, BOOK_NM_KOR_ABR, BOOK_NM_ENG, BOOK_NM_ENG_ABR, LAST_PAGE) VALUES ('스가랴', '슥', 'Zechariah', 'ZEC', '14')
INSERT INTO "SCAL"."BIBLE_MASTER" (BOOK_NM_KOR, BOOK_NM_KOR_ABR, BOOK_NM_ENG, BOOK_NM_ENG_ABR, LAST_PAGE) VALUES ('말라기', '말', 'Malachi', 'MAL', '4')
INSERT INTO "SCAL"."BIBLE_MASTER" (BOOK_NM_KOR, BOOK_NM_KOR_ABR, BOOK_NM_ENG, BOOK_NM_ENG_ABR, LAST_PAGE) VALUES ('마태복음', '마', 'Matthew', 'MAT', '28')
INSERT INTO "SCAL"."BIBLE_MASTER" (BOOK_NM_KOR, BOOK_NM_KOR_ABR, BOOK_NM_ENG, BOOK_NM_ENG_ABR, LAST_PAGE) VALUES ('마가복음', '막', 'Mark', 'MAR', '16')
INSERT INTO "SCAL"."BIBLE_MASTER" (BOOK_NM_KOR, BOOK_NM_KOR_ABR, BOOK_NM_ENG, BOOK_NM_ENG_ABR, LAST_PAGE) VALUES ('누가복음', '눅', 'Luke', 'LUK', '24')
INSERT INTO "SCAL"."BIBLE_MASTER" (BOOK_NM_KOR, BOOK_NM_KOR_ABR, BOOK_NM_ENG, BOOK_NM_ENG_ABR, LAST_PAGE) VALUES ('요한복음', '요', 'John', 'JOH', '21')
INSERT INTO "SCAL"."BIBLE_MASTER" (BOOK_NM_KOR, BOOK_NM_KOR_ABR, BOOK_NM_ENG, BOOK_NM_ENG_ABR, LAST_PAGE) VALUES ('사도행전', '행', 'Acts', 'ACT', '28')
INSERT INTO "SCAL"."BIBLE_MASTER" (BOOK_NM_KOR, BOOK_NM_KOR_ABR, BOOK_NM_ENG, BOOK_NM_ENG_ABR, LAST_PAGE) VALUES ('로마서', '롬', 'Romans', 'ROM', '16')
INSERT INTO "SCAL"."BIBLE_MASTER" (BOOK_NM_KOR, BOOK_NM_KOR_ABR, BOOK_NM_ENG, BOOK_NM_ENG_ABR, LAST_PAGE) VALUES ('고린도전서', '고전', '1Corinthians', 'CO1', '16')
INSERT INTO "SCAL"."BIBLE_MASTER" (BOOK_NM_KOR, BOOK_NM_KOR_ABR, BOOK_NM_ENG, BOOK_NM_ENG_ABR, LAST_PAGE) VALUES ('고린도후서', '고후', '2Corinthians', 'CO2', '13')
INSERT INTO "SCAL"."BIBLE_MASTER" (BOOK_NM_KOR, BOOK_NM_KOR_ABR, BOOK_NM_ENG, BOOK_NM_ENG_ABR, LAST_PAGE) VALUES ('갈라디아서', '갈', 'Galatians', 'GAL', '6')
INSERT INTO "SCAL"."BIBLE_MASTER" (BOOK_NM_KOR, BOOK_NM_KOR_ABR, BOOK_NM_ENG, BOOK_NM_ENG_ABR, LAST_PAGE) VALUES ('에베소서', '엡', 'Ephesians', 'EPH', '6')
INSERT INTO "SCAL"."BIBLE_MASTER" (BOOK_NM_KOR, BOOK_NM_KOR_ABR, BOOK_NM_ENG, BOOK_NM_ENG_ABR, LAST_PAGE) VALUES ('빌립보서', '빌', 'Philippians', 'PHI', '4')
INSERT INTO "SCAL"."BIBLE_MASTER" (BOOK_NM_KOR, BOOK_NM_KOR_ABR, BOOK_NM_ENG, BOOK_NM_ENG_ABR, LAST_PAGE) VALUES ('골로새서', '골', 'Colossians', 'COL', '4')
INSERT INTO "SCAL"."BIBLE_MASTER" (BOOK_NM_KOR, BOOK_NM_KOR_ABR, BOOK_NM_ENG, BOOK_NM_ENG_ABR, LAST_PAGE) VALUES ('데살로니가전서', '살전', '1Thessalonians', 'TH1', '5')
INSERT INTO "SCAL"."BIBLE_MASTER" (BOOK_NM_KOR, BOOK_NM_KOR_ABR, BOOK_NM_ENG, BOOK_NM_ENG_ABR, LAST_PAGE) VALUES ('데살로니가후서', '살후', '2Thessalonians', 'TH2', '3')
INSERT INTO "SCAL"."BIBLE_MASTER" (BOOK_NM_KOR, BOOK_NM_KOR_ABR, BOOK_NM_ENG, BOOK_NM_ENG_ABR, LAST_PAGE) VALUES ('디모데전서', '전', '1Timothy', 'TI1', '6')
INSERT INTO "SCAL"."BIBLE_MASTER" (BOOK_NM_KOR, BOOK_NM_KOR_ABR, BOOK_NM_ENG, BOOK_NM_ENG_ABR, LAST_PAGE) VALUES ('디모데후서', '후', '2Timothy', 'TI2', '4')
INSERT INTO "SCAL"."BIBLE_MASTER" (BOOK_NM_KOR, BOOK_NM_KOR_ABR, BOOK_NM_ENG, BOOK_NM_ENG_ABR, LAST_PAGE) VALUES ('디도서', '딛', 'Titus', 'TIT', '3')
INSERT INTO "SCAL"."BIBLE_MASTER" (BOOK_NM_KOR, BOOK_NM_KOR_ABR, BOOK_NM_ENG, BOOK_NM_ENG_ABR, LAST_PAGE) VALUES ('빌레몬서', '몬', 'Philemon', 'PHM', '1')
INSERT INTO "SCAL"."BIBLE_MASTER" (BOOK_NM_KOR, BOOK_NM_KOR_ABR, BOOK_NM_ENG, BOOK_NM_ENG_ABR, LAST_PAGE) VALUES ('히브리서', '히', 'Hebrews', 'HEB', '13')
INSERT INTO "SCAL"."BIBLE_MASTER" (BOOK_NM_KOR, BOOK_NM_KOR_ABR, BOOK_NM_ENG, BOOK_NM_ENG_ABR, LAST_PAGE) VALUES ('야고보서', '약', 'James', 'JAM', '5')
INSERT INTO "SCAL"."BIBLE_MASTER" (BOOK_NM_KOR, BOOK_NM_KOR_ABR, BOOK_NM_ENG, BOOK_NM_ENG_ABR, LAST_PAGE) VALUES ('베드로전서', '벧전', '1Peter', 'PE1', '5')
INSERT INTO "SCAL"."BIBLE_MASTER" (BOOK_NM_KOR, BOOK_NM_KOR_ABR, BOOK_NM_ENG, BOOK_NM_ENG_ABR, LAST_PAGE) VALUES ('베드로후서', '벧후', '2Peter', 'PE2', '3')
INSERT INTO "SCAL"."BIBLE_MASTER" (BOOK_NM_KOR, BOOK_NM_KOR_ABR, BOOK_NM_ENG, BOOK_NM_ENG_ABR, LAST_PAGE) VALUES ('요한1서', '요일', '1John', 'JO1', '5')
INSERT INTO "SCAL"."BIBLE_MASTER" (BOOK_NM_KOR, BOOK_NM_KOR_ABR, BOOK_NM_ENG, BOOK_NM_ENG_ABR, LAST_PAGE) VALUES ('요한2서', '요이', '2John', 'JO2', '1')
INSERT INTO "SCAL"."BIBLE_MASTER" (BOOK_NM_KOR, BOOK_NM_KOR_ABR, BOOK_NM_ENG, BOOK_NM_ENG_ABR, LAST_PAGE) VALUES ('요한3서', '요삼', '3John', 'JO3', '1')
INSERT INTO "SCAL"."BIBLE_MASTER" (BOOK_NM_KOR, BOOK_NM_KOR_ABR, BOOK_NM_ENG, BOOK_NM_ENG_ABR, LAST_PAGE) VALUES ('유다서', '유', 'Jude', 'JUD', '1')
INSERT INTO "SCAL"."BIBLE_MASTER" (BOOK_NM_KOR, BOOK_NM_KOR_ABR, BOOK_NM_ENG, BOOK_NM_ENG_ABR, LAST_PAGE) VALUES ('요한계시록', '계', 'Revelation', 'REV', '22')


-- 성경읽기 기록
create table BIBLE_READER (
  BOOK_SEQ        NUMBER(5,0),
  BOOK_NM_KOR_ABR varchar(50),
  BOOK_PAGE       NUMBER(5,0),
  READ_DATE       Date,
  CONSTRAINT BIBLE_READER PRIMARY KEY ( BOOK_SEQ, BOOK_NM_KOR_ABR, BOOK_PAGE ) ENABLE
);