CREATE TABLE COM_USER
(
  USER_NO VARCHAR2(20) NOT NULL,
  USER_NM VARCHAR2(20),
  LOGIN_ID VARCHAR2(20),
  LOGIN_PW VARCHAR2(20),
  CLIENT_IP VARCHAR2(20),
  WRONG_PW_CNT NUMBER(4,0),
  LAST_LOGIN_DT DATE,
  CONSTRAINT COM_USER_PK PRIMARY KEY ( USER_NO ) ENABLE
)
;

-- 성경
create table BIBLE_MASTER (
  BOOK_SEQ        NUMBER(5,0),
  BOOK_NM_KOR     varchar(50),
  BOOK_NM_KOR_ABR varchar(50),
  BOOK_NM_ENG     varchar(50),
  BOOK_NM_ENG_ABR varchar(50),
  LAST_PAGE       NUMBER(5,0),
  CONSTRAINT BIBLE_MASTER_PK PRIMARY KEY ( BOOK_SEQ ) ENABLE
);


-- 성경읽기 기록
drop table BIBLE_READER cascade constraints;
 
create table BIBLE_READER (
  USER_ID         varchar(50),
  READ_SEQ        NUMBER(5,0),
  BOOK_NM_KOR_ABR varchar(50),
  BOOK_PAGE       NUMBER(5,0),
  READ_DATE       Date,
  CONSTRAINT BIBLE_READER_PK PRIMARY KEY ( USER_ID, READ_SEQ, BOOK_NM_KOR_ABR, BOOK_PAGE ) ENABLE
);


Insert into BIBLE_MASTER (BOOK_SEQ,BOOK_NM_KOR,BOOK_NM_KOR_ABR,BOOK_NM_ENG,BOOK_NM_ENG_ABR,LAST_PAGE,BOOK_SE) values (1,'창세기','창','Genesis','GEN',50,'모세오경');
Insert into BIBLE_MASTER (BOOK_SEQ,BOOK_NM_KOR,BOOK_NM_KOR_ABR,BOOK_NM_ENG,BOOK_NM_ENG_ABR,LAST_PAGE,BOOK_SE) values (2,'출애굽기','출','Exodus','EXO',40,'모세오경');
Insert into BIBLE_MASTER (BOOK_SEQ,BOOK_NM_KOR,BOOK_NM_KOR_ABR,BOOK_NM_ENG,BOOK_NM_ENG_ABR,LAST_PAGE,BOOK_SE) values (3,'레위기','레','Leviticus','LEV',27,'모세오경');
Insert into BIBLE_MASTER (BOOK_SEQ,BOOK_NM_KOR,BOOK_NM_KOR_ABR,BOOK_NM_ENG,BOOK_NM_ENG_ABR,LAST_PAGE,BOOK_SE) values (4,'민수기','민','Numbers','NUM',36,'모세오경');
Insert into BIBLE_MASTER (BOOK_SEQ,BOOK_NM_KOR,BOOK_NM_KOR_ABR,BOOK_NM_ENG,BOOK_NM_ENG_ABR,LAST_PAGE,BOOK_SE) values (5,'신명기','신','Deuteronomy','DEU',34,'모세오경');
Insert into BIBLE_MASTER (BOOK_SEQ,BOOK_NM_KOR,BOOK_NM_KOR_ABR,BOOK_NM_ENG,BOOK_NM_ENG_ABR,LAST_PAGE,BOOK_SE) values (6,'여호수아','수','Joshua','JOS',24,'역사서');
Insert into BIBLE_MASTER (BOOK_SEQ,BOOK_NM_KOR,BOOK_NM_KOR_ABR,BOOK_NM_ENG,BOOK_NM_ENG_ABR,LAST_PAGE,BOOK_SE) values (7,'사사기','삿','Judges','JDG',21,'역사서');
Insert into BIBLE_MASTER (BOOK_SEQ,BOOK_NM_KOR,BOOK_NM_KOR_ABR,BOOK_NM_ENG,BOOK_NM_ENG_ABR,LAST_PAGE,BOOK_SE) values (8,'룻기','룻','Ruth','RTH',4,'역사서');
Insert into BIBLE_MASTER (BOOK_SEQ,BOOK_NM_KOR,BOOK_NM_KOR_ABR,BOOK_NM_ENG,BOOK_NM_ENG_ABR,LAST_PAGE,BOOK_SE) values (9,'사무엘상','삼상','1Samuel','SA1',31,'역사서');
Insert into BIBLE_MASTER (BOOK_SEQ,BOOK_NM_KOR,BOOK_NM_KOR_ABR,BOOK_NM_ENG,BOOK_NM_ENG_ABR,LAST_PAGE,BOOK_SE) values (10,'사무엘하','삼하','2Samuel','SA2',24,'역사서');
Insert into BIBLE_MASTER (BOOK_SEQ,BOOK_NM_KOR,BOOK_NM_KOR_ABR,BOOK_NM_ENG,BOOK_NM_ENG_ABR,LAST_PAGE,BOOK_SE) values (11,'열왕기상','왕상','1Kings','KI1',22,'역사서');
Insert into BIBLE_MASTER (BOOK_SEQ,BOOK_NM_KOR,BOOK_NM_KOR_ABR,BOOK_NM_ENG,BOOK_NM_ENG_ABR,LAST_PAGE,BOOK_SE) values (12,'열왕기하','왕하','2Kings','KI2',25,'역사서');
Insert into BIBLE_MASTER (BOOK_SEQ,BOOK_NM_KOR,BOOK_NM_KOR_ABR,BOOK_NM_ENG,BOOK_NM_ENG_ABR,LAST_PAGE,BOOK_SE) values (13,'역대상','대상','1Chronicles','CH1',29,'역사서');
Insert into BIBLE_MASTER (BOOK_SEQ,BOOK_NM_KOR,BOOK_NM_KOR_ABR,BOOK_NM_ENG,BOOK_NM_ENG_ABR,LAST_PAGE,BOOK_SE) values (14,'역대하','대하','2Chronicles','CH2',36,'역사서');
Insert into BIBLE_MASTER (BOOK_SEQ,BOOK_NM_KOR,BOOK_NM_KOR_ABR,BOOK_NM_ENG,BOOK_NM_ENG_ABR,LAST_PAGE,BOOK_SE) values (15,'에스라','스','Ezra','EZR',10,'역사서');
Insert into BIBLE_MASTER (BOOK_SEQ,BOOK_NM_KOR,BOOK_NM_KOR_ABR,BOOK_NM_ENG,BOOK_NM_ENG_ABR,LAST_PAGE,BOOK_SE) values (16,'느헤미야','느','Nehemiah','NEH',13,'역사서');
Insert into BIBLE_MASTER (BOOK_SEQ,BOOK_NM_KOR,BOOK_NM_KOR_ABR,BOOK_NM_ENG,BOOK_NM_ENG_ABR,LAST_PAGE,BOOK_SE) values (17,'에스더','에','Esther','EST',10,'역사서');
Insert into BIBLE_MASTER (BOOK_SEQ,BOOK_NM_KOR,BOOK_NM_KOR_ABR,BOOK_NM_ENG,BOOK_NM_ENG_ABR,LAST_PAGE,BOOK_SE) values (18,'욥기','욥','Job','JOB',42,'시가서');
Insert into BIBLE_MASTER (BOOK_SEQ,BOOK_NM_KOR,BOOK_NM_KOR_ABR,BOOK_NM_ENG,BOOK_NM_ENG_ABR,LAST_PAGE,BOOK_SE) values (19,'시편','시','Psalms','PSA',150,'시가서');
Insert into BIBLE_MASTER (BOOK_SEQ,BOOK_NM_KOR,BOOK_NM_KOR_ABR,BOOK_NM_ENG,BOOK_NM_ENG_ABR,LAST_PAGE,BOOK_SE) values (20,'잠언','잠','Proverbs','PRO',31,'시가서');
Insert into BIBLE_MASTER (BOOK_SEQ,BOOK_NM_KOR,BOOK_NM_KOR_ABR,BOOK_NM_ENG,BOOK_NM_ENG_ABR,LAST_PAGE,BOOK_SE) values (21,'전도서','전','Ecclesiastes','ECC',12,'시가서');
Insert into BIBLE_MASTER (BOOK_SEQ,BOOK_NM_KOR,BOOK_NM_KOR_ABR,BOOK_NM_ENG,BOOK_NM_ENG_ABR,LAST_PAGE,BOOK_SE) values (22,'아가','아','SongofSongs','SON',8,'시가서');
Insert into BIBLE_MASTER (BOOK_SEQ,BOOK_NM_KOR,BOOK_NM_KOR_ABR,BOOK_NM_ENG,BOOK_NM_ENG_ABR,LAST_PAGE,BOOK_SE) values (23,'이사야','사','Isaiah','ISA',66,'선지서');
Insert into BIBLE_MASTER (BOOK_SEQ,BOOK_NM_KOR,BOOK_NM_KOR_ABR,BOOK_NM_ENG,BOOK_NM_ENG_ABR,LAST_PAGE,BOOK_SE) values (24,'예레미야','렘','Jeremiah','JER',52,'선지서');
Insert into BIBLE_MASTER (BOOK_SEQ,BOOK_NM_KOR,BOOK_NM_KOR_ABR,BOOK_NM_ENG,BOOK_NM_ENG_ABR,LAST_PAGE,BOOK_SE) values (25,'예레미야 애가','애','Lamentations','LAM',5,'선지서');
Insert into BIBLE_MASTER (BOOK_SEQ,BOOK_NM_KOR,BOOK_NM_KOR_ABR,BOOK_NM_ENG,BOOK_NM_ENG_ABR,LAST_PAGE,BOOK_SE) values (26,'에스겔','겔','Ezekiel','EZE',48,'선지서');
Insert into BIBLE_MASTER (BOOK_SEQ,BOOK_NM_KOR,BOOK_NM_KOR_ABR,BOOK_NM_ENG,BOOK_NM_ENG_ABR,LAST_PAGE,BOOK_SE) values (27,'다니엘','단','Daniel','DAN',12,'선지서');
Insert into BIBLE_MASTER (BOOK_SEQ,BOOK_NM_KOR,BOOK_NM_KOR_ABR,BOOK_NM_ENG,BOOK_NM_ENG_ABR,LAST_PAGE,BOOK_SE) values (28,'호세아','호','Hosea','HOS',14,'선지서');
Insert into BIBLE_MASTER (BOOK_SEQ,BOOK_NM_KOR,BOOK_NM_KOR_ABR,BOOK_NM_ENG,BOOK_NM_ENG_ABR,LAST_PAGE,BOOK_SE) values (29,'요엘','욜','Joel','JOE',3,'선지서');
Insert into BIBLE_MASTER (BOOK_SEQ,BOOK_NM_KOR,BOOK_NM_KOR_ABR,BOOK_NM_ENG,BOOK_NM_ENG_ABR,LAST_PAGE,BOOK_SE) values (30,'아모스','암','Amos','AMO',9,'선지서');
Insert into BIBLE_MASTER (BOOK_SEQ,BOOK_NM_KOR,BOOK_NM_KOR_ABR,BOOK_NM_ENG,BOOK_NM_ENG_ABR,LAST_PAGE,BOOK_SE) values (31,'오바댜','옵','Obadiah','OBA',1,'선지서');
Insert into BIBLE_MASTER (BOOK_SEQ,BOOK_NM_KOR,BOOK_NM_KOR_ABR,BOOK_NM_ENG,BOOK_NM_ENG_ABR,LAST_PAGE,BOOK_SE) values (32,'요나','욘','Jonah','JON',4,'선지서');
Insert into BIBLE_MASTER (BOOK_SEQ,BOOK_NM_KOR,BOOK_NM_KOR_ABR,BOOK_NM_ENG,BOOK_NM_ENG_ABR,LAST_PAGE,BOOK_SE) values (33,'미가','미','Micah','MIC',7,'선지서');
Insert into BIBLE_MASTER (BOOK_SEQ,BOOK_NM_KOR,BOOK_NM_KOR_ABR,BOOK_NM_ENG,BOOK_NM_ENG_ABR,LAST_PAGE,BOOK_SE) values (34,'나훔','나','Nahum','NAH',3,'선지서');
Insert into BIBLE_MASTER (BOOK_SEQ,BOOK_NM_KOR,BOOK_NM_KOR_ABR,BOOK_NM_ENG,BOOK_NM_ENG_ABR,LAST_PAGE,BOOK_SE) values (35,'하박국','합','Habakkuk','HAB',3,'선지서');
Insert into BIBLE_MASTER (BOOK_SEQ,BOOK_NM_KOR,BOOK_NM_KOR_ABR,BOOK_NM_ENG,BOOK_NM_ENG_ABR,LAST_PAGE,BOOK_SE) values (36,'스바냐','습','Zephaniah','ZEP',3,'선지서');
Insert into BIBLE_MASTER (BOOK_SEQ,BOOK_NM_KOR,BOOK_NM_KOR_ABR,BOOK_NM_ENG,BOOK_NM_ENG_ABR,LAST_PAGE,BOOK_SE) values (37,'학개','학','Haggai','HAG',2,'선지서');
Insert into BIBLE_MASTER (BOOK_SEQ,BOOK_NM_KOR,BOOK_NM_KOR_ABR,BOOK_NM_ENG,BOOK_NM_ENG_ABR,LAST_PAGE,BOOK_SE) values (38,'스가랴','슥','Zechariah','ZEC',14,'선지서');
Insert into BIBLE_MASTER (BOOK_SEQ,BOOK_NM_KOR,BOOK_NM_KOR_ABR,BOOK_NM_ENG,BOOK_NM_ENG_ABR,LAST_PAGE,BOOK_SE) values (39,'말라기','말','Malachi','MAL',4,'선지서');
Insert into BIBLE_MASTER (BOOK_SEQ,BOOK_NM_KOR,BOOK_NM_KOR_ABR,BOOK_NM_ENG,BOOK_NM_ENG_ABR,LAST_PAGE,BOOK_SE) values (40,'마태복음','마','Matthew','MAT',28,'복음/역사서');
Insert into BIBLE_MASTER (BOOK_SEQ,BOOK_NM_KOR,BOOK_NM_KOR_ABR,BOOK_NM_ENG,BOOK_NM_ENG_ABR,LAST_PAGE,BOOK_SE) values (41,'마가복음','막','Mark','MAR',16,'복음/역사서');
Insert into BIBLE_MASTER (BOOK_SEQ,BOOK_NM_KOR,BOOK_NM_KOR_ABR,BOOK_NM_ENG,BOOK_NM_ENG_ABR,LAST_PAGE,BOOK_SE) values (42,'누가복음','눅','Luke','LUK',24,'복음/역사서');
Insert into BIBLE_MASTER (BOOK_SEQ,BOOK_NM_KOR,BOOK_NM_KOR_ABR,BOOK_NM_ENG,BOOK_NM_ENG_ABR,LAST_PAGE,BOOK_SE) values (43,'요한복음','요','John','JOH',21,'복음/역사서');
Insert into BIBLE_MASTER (BOOK_SEQ,BOOK_NM_KOR,BOOK_NM_KOR_ABR,BOOK_NM_ENG,BOOK_NM_ENG_ABR,LAST_PAGE,BOOK_SE) values (44,'사도행전','행','Acts','ACT',28,'복음/역사서');
Insert into BIBLE_MASTER (BOOK_SEQ,BOOK_NM_KOR,BOOK_NM_KOR_ABR,BOOK_NM_ENG,BOOK_NM_ENG_ABR,LAST_PAGE,BOOK_SE) values (45,'로마서','롬','Romans','ROM',16,'서신서');
Insert into BIBLE_MASTER (BOOK_SEQ,BOOK_NM_KOR,BOOK_NM_KOR_ABR,BOOK_NM_ENG,BOOK_NM_ENG_ABR,LAST_PAGE,BOOK_SE) values (46,'고린도전서','고전','1Corinthians','CO1',16,'서신서');
Insert into BIBLE_MASTER (BOOK_SEQ,BOOK_NM_KOR,BOOK_NM_KOR_ABR,BOOK_NM_ENG,BOOK_NM_ENG_ABR,LAST_PAGE,BOOK_SE) values (47,'고린도후서','고후','2Corinthians','CO2',13,'서신서');
Insert into BIBLE_MASTER (BOOK_SEQ,BOOK_NM_KOR,BOOK_NM_KOR_ABR,BOOK_NM_ENG,BOOK_NM_ENG_ABR,LAST_PAGE,BOOK_SE) values (48,'갈라디아서','갈','Galatians','GAL',6,'서신서');
Insert into BIBLE_MASTER (BOOK_SEQ,BOOK_NM_KOR,BOOK_NM_KOR_ABR,BOOK_NM_ENG,BOOK_NM_ENG_ABR,LAST_PAGE,BOOK_SE) values (49,'에베소서','엡','Ephesians','EPH',6,'서신서');
Insert into BIBLE_MASTER (BOOK_SEQ,BOOK_NM_KOR,BOOK_NM_KOR_ABR,BOOK_NM_ENG,BOOK_NM_ENG_ABR,LAST_PAGE,BOOK_SE) values (50,'빌립보서','빌','Philippians','PHI',4,'서신서');
Insert into BIBLE_MASTER (BOOK_SEQ,BOOK_NM_KOR,BOOK_NM_KOR_ABR,BOOK_NM_ENG,BOOK_NM_ENG_ABR,LAST_PAGE,BOOK_SE) values (51,'골로새서','골','Colossians','COL',4,'서신서');
Insert into BIBLE_MASTER (BOOK_SEQ,BOOK_NM_KOR,BOOK_NM_KOR_ABR,BOOK_NM_ENG,BOOK_NM_ENG_ABR,LAST_PAGE,BOOK_SE) values (52,'데살로니가전서','살전','1Thessalonians','TH1',5,'서신서');
Insert into BIBLE_MASTER (BOOK_SEQ,BOOK_NM_KOR,BOOK_NM_KOR_ABR,BOOK_NM_ENG,BOOK_NM_ENG_ABR,LAST_PAGE,BOOK_SE) values (53,'데살로니가후서','살후','2Thessalonians','TH2',3,'서신서');
Insert into BIBLE_MASTER (BOOK_SEQ,BOOK_NM_KOR,BOOK_NM_KOR_ABR,BOOK_NM_ENG,BOOK_NM_ENG_ABR,LAST_PAGE,BOOK_SE) values (54,'디모데전서','딤전','1Timothy','TI1',6,'서신서');
Insert into BIBLE_MASTER (BOOK_SEQ,BOOK_NM_KOR,BOOK_NM_KOR_ABR,BOOK_NM_ENG,BOOK_NM_ENG_ABR,LAST_PAGE,BOOK_SE) values (55,'디모데후서','딤후','2Timothy','TI2',4,'서신서');
Insert into BIBLE_MASTER (BOOK_SEQ,BOOK_NM_KOR,BOOK_NM_KOR_ABR,BOOK_NM_ENG,BOOK_NM_ENG_ABR,LAST_PAGE,BOOK_SE) values (56,'디도서','딛','Titus','TIT',3,'서신서');
Insert into BIBLE_MASTER (BOOK_SEQ,BOOK_NM_KOR,BOOK_NM_KOR_ABR,BOOK_NM_ENG,BOOK_NM_ENG_ABR,LAST_PAGE,BOOK_SE) values (57,'빌레몬서','몬','Philemon','PHM',1,'서신서');
Insert into BIBLE_MASTER (BOOK_SEQ,BOOK_NM_KOR,BOOK_NM_KOR_ABR,BOOK_NM_ENG,BOOK_NM_ENG_ABR,LAST_PAGE,BOOK_SE) values (58,'히브리서','히','Hebrews','HEB',13,'서신서');
Insert into BIBLE_MASTER (BOOK_SEQ,BOOK_NM_KOR,BOOK_NM_KOR_ABR,BOOK_NM_ENG,BOOK_NM_ENG_ABR,LAST_PAGE,BOOK_SE) values (59,'야고보서','약','James','JAM',5,'서신서');
Insert into BIBLE_MASTER (BOOK_SEQ,BOOK_NM_KOR,BOOK_NM_KOR_ABR,BOOK_NM_ENG,BOOK_NM_ENG_ABR,LAST_PAGE,BOOK_SE) values (60,'베드로전서','벧전','1Peter','PE1',5,'서신서');
Insert into BIBLE_MASTER (BOOK_SEQ,BOOK_NM_KOR,BOOK_NM_KOR_ABR,BOOK_NM_ENG,BOOK_NM_ENG_ABR,LAST_PAGE,BOOK_SE) values (61,'베드로후서','벧후','2Peter','PE2',3,'서신서');
Insert into BIBLE_MASTER (BOOK_SEQ,BOOK_NM_KOR,BOOK_NM_KOR_ABR,BOOK_NM_ENG,BOOK_NM_ENG_ABR,LAST_PAGE,BOOK_SE) values (62,'요한1서','요일','1John','JO1',5,'서신서');
Insert into BIBLE_MASTER (BOOK_SEQ,BOOK_NM_KOR,BOOK_NM_KOR_ABR,BOOK_NM_ENG,BOOK_NM_ENG_ABR,LAST_PAGE,BOOK_SE) values (63,'요한2서','요이','2John','JO2',1,'서신서');
Insert into BIBLE_MASTER (BOOK_SEQ,BOOK_NM_KOR,BOOK_NM_KOR_ABR,BOOK_NM_ENG,BOOK_NM_ENG_ABR,LAST_PAGE,BOOK_SE) values (64,'요한3서','요삼','3John','JO3',1,'서신서');
Insert into BIBLE_MASTER (BOOK_SEQ,BOOK_NM_KOR,BOOK_NM_KOR_ABR,BOOK_NM_ENG,BOOK_NM_ENG_ABR,LAST_PAGE,BOOK_SE) values (65,'유다서','유','Jude','JUD',1,'서신서');
Insert into BIBLE_MASTER (BOOK_SEQ,BOOK_NM_KOR,BOOK_NM_KOR_ABR,BOOK_NM_ENG,BOOK_NM_ENG_ABR,LAST_PAGE,BOOK_SE) values (66,'요한계시록','계','Revelation','REV',22,'예언서');



-- 다음 읽을 장 추천
select 
  AA.BOOK_NM_KOR_ABR||':'||
  (select (nvl(max(BB.BOOK_PAGE),0)+1)
     from BIBLE_READER BB
    where AA.BOOK_NM_KOR_ABR = BB.BOOK_NM_KOR_ABR 
      and BB.USER_ID = 'UK330'
      and BB.READ_SEQ = '1') as RECOM_BOOM
from BIBLE_MASTER AA
where AA.BOOK_SEQ = nvl((select max(A.BOOK_SEQ) as MAX_BOOK_SEQ
                           from BIBLE_MASTER A, BIBLE_READER B
                          where A.BOOK_NM_KOR_ABR = B.BOOK_NM_KOR_ABR
                            and B.USER_ID = 'UK330'
                            and A.BOOK_SE = '선지서'
                            and B.READ_SEQ = '1' )
                        ,(select min(BOOK_SEQ) from BIBLE_MASTER where BOOK_SE = '선지서')
                        )
;