CREATE TABLE COM_USER
(
  USER_NO VARCHAR2(20) NOT NULL,
  USER_NM VARCHAR2(20),
  LOGIN_ID VARCHAR2(20),
  LOGIN_PW VARCHAR2(20),
  CLIENT_IP VARCHAR2(20),
  WRONG_PW_CNT NUMBER(4,0),
  LAST_LOGIN_DT DATE,
  CONSTRAINT COM_USER_PK PRIMARY KEY ( USER_NO ) ENABLE
)
;
